In [1]:
pip install pandas numpy scikit-learn matplotlib openpyxl


   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Note: you may need to restart the kernel to use updated packages.


In [2]:
import pandas as pd
import numpy as np

df = pd.read_excel("Online Retail (1).xlsx")
print(f"Shape: {df.shape}")
print(f"\nColumn types:\n{df.dtypes}")
print(f"\nMissing values:\n{df.isnull().sum()}")
print(f"\nFirst rows:\n{df.head()}")

Shape: (541909, 8)

Column types:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[ns]
UnitPrice             float64
CustomerID            float64
Country                object
dtype: object

Missing values:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

First rows:
  InvoiceNo StockCode                          Description  Quantity  \
0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1    536365     71053                  WHITE METAL LANTERN         6   
2    536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   

          InvoiceDate  UnitPrice  CustomerID         Country

In [3]:
df.head()


,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom


In [4]:
df[df['Quantity']<0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom


In [82]:
df['StockCode'].unique().shape

(4070,)

In [10]:
df['Description'].unique().shape

(4224,)

In [83]:
df.groupby("StockCode")["Description"].nunique().sort_values(ascending=False)

StockCode
20713        8
23084        7
21830        6
85175        6
72807A       5
            ..
DCGS0055     0
DCGS0057     0
DCGS0066P    0
DCGS0071     0
DCGS0072     0
Name: Description, Length: 4070, dtype: int64

In [11]:
df['CustomerID'].unique().shape

(4373,)

## Task 1: Data Profiling and Missing Values (~25 minutes)

### 1.1 — Profile the raw data

Compute a comprehensive profile of the dataset:

- Number of rows, columns, and memory usage
- Missing value counts and percentages for each column
- Number of unique values per column
- Basic statistics for numeric columns (min, max, mean, median, std)


In [12]:
rows, cols = df.shape

print("Number of rows:", rows)
print("Number of columns:", cols)

memory_usage = df.memory_usage(deep=True).sum() / (1024**2)
print("Memory usage (MB):", round(memory_usage, 2))

Number of rows: 541909
Number of columns: 8
Memory usage (MB): 126.18


In [13]:
missing_count = df.isnull().sum()

missing_percent = (missing_count / len(df)) * 100

missing_df = pd.DataFrame({
    "Missing Count": missing_count,
    "Missing Percent": missing_percent
})

print(missing_df)

             Missing Count  Missing Percent
InvoiceNo                0         0.000000
StockCode                0         0.000000
Description           1454         0.268311
Quantity                 0         0.000000
InvoiceDate              0         0.000000
UnitPrice                0         0.000000
CustomerID          135080        24.926694
Country                  0         0.000000


In [14]:
unique_values = df.nunique()

print("Unique values per column:")
print(unique_values)

Unique values per column:
InvoiceNo      25900
StockCode       4070
Description     4223
Quantity         722
InvoiceDate    23260
UnitPrice       1630
CustomerID      4372
Country           38
dtype: int64


In [18]:
df.describe()

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303


### 1.2 — Classify the missing data types

The two columns with significant missing values are `CustomerID` and `Description`.

For each:
- Determine whether the missingness is MNAR, MAR, or MCAR. Justify your answer with evidence (e.g., compare rows with and without missing values — do they differ systematically in other columns?).
- Decide on a strategy: deletion, imputation, or indicator column. Justify your choice.

Guiding questions:
- Are transactions with missing `CustomerID` different from those with a `CustomerID`? Check the distribution of `Country`, `Quantity`, and `UnitPrice` for both groups.
- Do transactions with missing `Description` have valid `StockCode` values? Could you recover descriptions from other rows with the same `StockCode`?

In [39]:
df_cust =df[df['CustomerID'].isna()]
df_cust['Country'].unique()

array(['United Kingdom', 'EIRE', 'Bahrain', 'Israel', 'Hong Kong',
       'Unspecified', 'France', 'Switzerland', 'Portugal'], dtype=object)

In [43]:
df_cust.shape

(135080, 8)

In [51]:
countries = ['United Kingdom', 'EIRE', 'Bahrain', 'Israel', 'Hong Kong', 'Unspecified', 'France', 'Switzerland', 'Portugal']

df_special_countryies = df[df['Country'].isin(countries)]
df_special_countryies.shape

(516802, 8)

In [60]:
df[df['Country']=='United Kingdom'].shape

(495478, 8)

In [61]:
df_cust[df_cust['Country']== 'United Kingdom'].shape

(133600, 8)

In [62]:
missing_stats = (
    df.groupby("Country")["CustomerID"]
      .agg(
          total_rows="count",
          missing_count=lambda x: x.isna().sum(),
          missing_percent=lambda x: x.isna().mean()*100
      )
      .sort_values("missing_percent", ascending=False)
)

print(missing_stats)

                      total_rows  missing_count  missing_percent
Country                                                         
Hong Kong                      0            288       100.000000
Unspecified                  244            202        45.291480
United Kingdom            361878         133600        26.963861
Israel                       250             47        15.824916
Bahrain                       17              2        10.526316
EIRE                        7485            711         8.674963
Switzerland                 1877            125         6.243756
Portugal                    1480             39         2.567479
France                      8491             66         0.771298
Canada                       151              0         0.000000
Australia                   1259              0         0.000000
Brazil                        32              0         0.000000
Belgium                     2069              0         0.000000
Austria                  

In [65]:
df[df['Country']=='Hong Kong']

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
69623,541975,22620,4 TRADITIONAL SPINNING TOPS,60,2011-01-24 14:24:00,1.25,NaN,Hong Kong
69624,541975,85183B,CHARLIE & LOLA WASTEPAPER BIN FLORA,6,2011-01-24 14:24:00,3.75,NaN,Hong Kong
69625,541975,85183A,CHARLIE & LOLA WASTEPAPER BIN BLUE,6,2011-01-24 14:24:00,3.75,NaN,Hong Kong
69626,541975,16236,KITTY PENCIL ERASERS,28,2011-01-24 14:24:00,0.21,NaN,Hong Kong
69627,541975,21058,PARTY INVITES WOODLAND,12,2011-01-24 14:24:00,0.85,NaN,Hong Kong
...,...,...,...,...,...,...,...,...
423776,573154,22452,MEASURING TAPE BABUSHKA PINK,30,2011-10-28 08:20:00,2.95,NaN,Hong Kong
423777,573154,22492,MINI PAINT SET VINTAGE,36,2011-10-28 08:20:00,0.65,NaN,Hong Kong
423778,573154,23328,SET 6 SCHOOL MILK BOTTLES IN CRATE,8,2011-10-28 08:20:00,3.75,NaN,Hong Kong
465423,C576233,M,Manual,-1,2011-11-14 13:26:00,326.10,NaN,Hong Kong


In [53]:
df_desc=df[df['Description'].isna()]
df_desc['UnitPrice'].unique()

array([0.])

In [59]:
df[ (df['Description'].isna()) | (df['Description'] == 0) | (df['Description'] == '0') ].shape
#output 1454 rows

(1454, 8)

In [57]:
df_desc.shape

(1454, 8)

In [70]:
df[df['UnitPrice']==0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
536981,581234,72817,NaN,27,2011-12-08 10:33:00,0.0,NaN,United Kingdom
538504,581406,46000M,POLYESTER FILLER PAD 45x45cm,240,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538505,581406,46000S,POLYESTER FILLER PAD 40x40cm,300,2011-12-08 13:58:00,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,2011-12-08 14:06:00,0.0,NaN,United Kingdom


In [80]:
df[df['UnitPrice']<0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,NaN,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,NaN,United Kingdom


In [79]:
df_unit_price=df[(df['UnitPrice'] == 0) & (df['Description'].notna())]
df_unit_price['Country'].unique()


array(['United Kingdom', 'Germany', 'EIRE', 'Switzerland', 'Australia',
       'Spain', 'Netherlands', 'RSA', 'France', 'Norway'], dtype=object)

### 1. CustomerID

To investigate the missingness pattern, transactions with and without `CustomerID` were compared across other variables such as `Country`, `Quantity`, and `UnitPrice`.

The analysis shows that missing `CustomerID` values occur more frequently in certain countries (e.g., United Kingdom, Hong Kong, and Unspecified), while many other countries have no missing values. This indicates that the probability of a missing `CustomerID` depends on another observed variable (`Country`). The distributions of `Quantity` and `UnitPrice` for transactions with and without `CustomerID` are otherwise similar, suggesting that these rows still represent valid transactions.

**Classification:** MAR (Missing At Random)

**Strategy:**  
Rows with missing `CustomerID` will be removed from the dataset. Since `CustomerID` is a unique identifier, it cannot be reliably imputed. Additionally, customer-level analyses require valid identifiers, so removing these rows ensures data consistency.

### 2. Description

Rows with missing `Description` were examined to determine whether other product information was available. These transactions typically have `UnitPrice = 0` and often also have missing `CustomerID`. Although a valid `StockCode` may exist, these records do not appear to represent normal product sales and instead likely correspond to adjustments, internal records, or other non-standard transactions.

Because the missingness is related to the nature of the transaction itself (e.g., non-product records), the absence of descriptions is not random.

**Classification:** MNAR (Missing Not At Random)

**Strategy:**  
Rows with missing `Description` will be removed from the dataset because they do not represent valid retail transactions and cannot be meaningfully imputed.

In [84]:
#next step


### 1.3 — Handle the missing values

Apply your chosen strategies. Document what you did and why. After handling missing values, print the remaining missing value counts to confirm.

### Deliverable for Task 1

A profiling summary, a written classification of missing data types with evidence, and clean handling with documentation.


#### CustomerID

The missing values in `CustomerID` were classified as **MAR (Missing At Random)** because the probability of missing values varies across countries. Some countries show higher missing percentages, while others contain no missing values, indicating that the missingness is related to another observed variable (`Country`).  

Since `CustomerID` is a unique identifier, it cannot be reliably imputed. Therefore, rows with missing `CustomerID` were removed from the dataset to ensure that all remaining transactions can be associated with a valid customer.

#### Description

The missing values in `Description` were classified as **MNAR (Missing Not At Random)**. Examination of these rows showed that all transactions with missing descriptions have `UnitPrice = 0`, and many also have missing `CustomerID`. This suggests that these rows represent adjustments, system records, or other non-product transactions rather than actual retail sales.

Instead of only removing rows with missing descriptions, all rows with `UnitPrice = 0` were removed. This approach ensures that all non-sale transactions are filtered out, including those that still contain a description but have zero price.

#### Implementation

In [85]:
# Remove rows with missing CustomerID
df = df.dropna(subset=["CustomerID"])

# Remove non-sale records (UnitPrice = 0)
df = df[df["UnitPrice"] > 0]

# Confirm that missing values were handled
df.isna().sum()

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [86]:
df.shape

(406789, 8)

## Task 2: Cleaning Invalid and Anomalous Records (~25 minutes)

### 2.1 — Identify cancellations

Invoices starting with "C" are cancellations. These have negative quantities and represent returns, not purchases.

- Count how many cancellation transactions exist.
- Decide whether to keep, remove, or flag them. Think about the downstream task: if you later want to predict customer churn or build a recommender, how do cancellations affect the analysis?


In [87]:
cancellations = df[df["InvoiceNo"].astype(str).str.startswith("C")]
cancellations

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527.0,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311.0,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548.0,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548.0,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397.0,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498.0,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311.0,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315.0,United Kingdom


In [88]:
cancellations["InvoiceNo"].nunique()

3654

In [89]:
cancellations["CustomerID"].nunique()

1589

In [91]:
cancellations.nunique()

InvoiceNo      3654
StockCode      1920
Description    1945
Quantity        134
InvoiceDate    3586
UnitPrice       376
CustomerID     1589
Country          28
dtype: int64

In [92]:
cancellations["Quantity"].describe()

count     8905.000000
mean       -30.859966
std       1170.154939
min     -80995.000000
25%         -6.000000
50%         -2.000000
75%         -1.000000
max         -1.000000
Name: Quantity, dtype: float64

In [94]:
cancellations[cancellations['Quantity']==cancellations["Quantity"].min()]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
540422,C581484,23843,"PAPER CRAFT , LITTLE BIRDIE",-80995,2011-12-09 09:27:00,2.08,16446.0,United Kingdom


In [95]:
df["is_cancelled"] = df["InvoiceNo"].astype(str).str.startswith("C")

In [99]:
purchases = df[df["is_cancelled"] == False]
#for purchase analyse
returns = df[df["is_cancelled"] == True]
#for cancellation analysis

Instead of immediately removing cancellation transactions, a boolean column `is_cancelled` was created to flag invoices that start with "C". This approach preserves the information while allowing flexible filtering.

For analyses focused on purchases, only rows where `is_cancelled = False` can be used. If return behavior needs to be analyzed later, the flagged cancellation rows can still be examined.

### 2.2 — Handle invalid quantities and prices

Investigate records with:
- `Quantity <= 0` (that are not cancellations)
- `UnitPrice <= 0`
- Extreme outliers in `Quantity` or `UnitPrice`

For each category of invalid record:
- Count how many exist
- Decide what to do (remove, cap, flag) and justify

In [102]:
invalid_quantity = df[(df["Quantity"] <= 0) & (~df["InvoiceNo"].astype(str).str.startswith("C"))]

print("Invalid quantity records:", len(invalid_quantity))

Invalid quantity records: 0


In [103]:
df[["Quantity", "UnitPrice"]].describe()

,Quantity,UnitPrice
count,406789.000000,406789.000000
mean,12.028359,3.460811
std,247.927842,69.318561
min,-80995.000000,0.001000
25%,2.000000,1.250000
50%,5.000000,1.950000
75%,12.000000,3.750000
max,80995.000000,38970.000000


In [104]:
Q1 = df["Quantity"].quantile(0.25)
Q3 = df["Quantity"].quantile(0.75)
IQR = Q3 - Q1

outliers_quantity = df[(df["Quantity"] < Q1 - 1.5*IQR) | (df["Quantity"] > Q3 + 1.5*IQR)]

print("Quantity outliers:", len(outliers_quantity))

Quantity outliers: 26673


In [105]:
Q1 = df["UnitPrice"].quantile(0.25)
Q3 = df["UnitPrice"].quantile(0.75)
IQR = Q3 - Q1

outliers_price = df[(df["UnitPrice"] < Q1 - 1.5*IQR) | (df["UnitPrice"] > Q3 + 1.5*IQR)]

print("Price outliers:", len(outliers_price))

Price outliers: 36051


**Quantity ≤ 0 (non-cancellations)**  
Transactions with non-positive quantities that are not cancellations were checked. The analysis showed that all negative quantities correspond to cancellation invoices. Therefore, no additional invalid quantity records were found.

**UnitPrice ≤ 0**  
Records with zero prices were examined and were found to often correspond to missing product descriptions or system adjustments rather than real purchases. Since valid retail transactions should have a positive unit price, rows with `UnitPrice ≤ 0` were removed.

**Extreme outliers**  
Extreme values were observed in both `Quantity` and `UnitPrice`. For example, the maximum quantity reaches 80,995 units and the maximum price is 38,970 GBP. These values may represent legitimate bulk purchases or expensive items rather than data errors. Therefore, instead of removing them, these extreme values were flagged for further inspection.

### 2.3 — Clean and validate

Apply your cleaning rules. After cleaning, verify:
- No remaining negative quantities (unless you kept cancellations with a flag)
- No zero or negative prices
- Print the shape before and after cleaning

In [107]:
print("Negative quantities (non-cancellations):",
      len(df[(df["Quantity"] <= 0) & (~df["is_cancelled"])]))

print("Zero or negative prices:",
      len(df[df["UnitPrice"] <= 0]))

Negative quantities (non-cancellations): 0
Zero or negative prices: 0


In [108]:
# Shape: (541909, 8)  was first shape

In [109]:
df.shape

(406789, 9)

In [110]:
# (406789, 9) is current shape

In [111]:
df.isnull().sum()

InvoiceNo       0
StockCode       0
Description     0
Quantity        0
InvoiceDate     0
UnitPrice       0
CustomerID      0
Country         0
is_cancelled    0
dtype: int64

## Task 3: Categorical Data Challenges (~20 minutes)

### 3.1 — Analyze the Country column

- How many unique countries are there?
- What percentage of transactions come from the top 5 countries?
- How many countries have fewer than 50 transactions?

Create a cleaned version of the `Country` column that groups rare countries (fewer than 50 transactions) into an "Other" category. Compare the number of categories before and after.

In [112]:
df["Country"].nunique()

37

In [113]:
country_counts = df["Country"].value_counts()
top5 = country_counts.head(5)
top5_percentage = (top5.sum() / len(df)) * 100
print("Top 5 countries percentage:", top5_percentage)

Top 5 countries percentage: 95.83641642227298


In [114]:
rare_countries = country_counts[country_counts < 50]
print("Countries with fewer than 50 transactions:", len(rare_countries))

Countries with fewer than 50 transactions: 6


In [115]:
rare_country_list = rare_countries.index
df["Country_clean"] = df["Country"].apply(
    lambda x: "Other" if x in rare_country_list else x
)

In [117]:
print("Original country categories:", df["Country"].nunique())
print("Cleaned country categories:", df["Country_clean"].nunique())

Original country categories: 37
Cleaned country categories: 32


In [118]:
df.drop(columns=["Country"], inplace=True)

In [119]:
df.rename(columns={"Country_clean": "Country"}, inplace=True)

In [120]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,is_cancelled,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,False,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,False,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom
...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,False,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,False,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,False,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,False,France


The `Country` column was analyzed to understand the distribution of transactions across countries.

First, the number of unique countries in the dataset was calculated. The dataset contains **37 unique countries**, indicating a relatively high-cardinality categorical feature.

Next, the percentage of transactions coming from the top 5 countries was computed. The results show that the **top 5 countries account for approximately 95.84% of all transactions**, demonstrating a highly imbalanced distribution where most purchases originate from a small number of countries.

To further investigate the distribution, countries with fewer than **50 transactions** were identified. A total of **6 countries** fall into this category and are considered rare categories.

To simplify the dataset and reduce the impact of very rare categories, these countries were grouped into a single category labeled **"Other"**. This approach helps reduce noise and prevents models from overfitting to extremely small groups.

A new feature called `Country_clean` was created to represent the grouped countries. The number of categories decreased from **37 original categories** to **32 categories** after grouping rare countries.

Finally, the original `Country` column was removed, keeping only the cleaned version for further analysis.

### 3.2 — Analyze the StockCode column

`StockCode` is a high-cardinality categorical feature.

- How many unique stock codes exist?
- Are there non-product codes (e.g., postage, discounts, manual adjustments)? Identify them by looking at codes that are not purely numeric or have unusual patterns.
- Decide how to handle non-product codes for a product-level analysis.

In [121]:
df["StockCode"].nunique()

3684

In [128]:
df["StockCode"].unique()

array(['85123A', 71053, '84406B', ..., '90214Z', 90089, 23843],
      shape=(3684,), dtype=object)

In [132]:
df["StockCode"] = df["StockCode"].astype(str)
non_product_codes = df[~df["StockCode"].str.match(r"^\d+[A-Z]?$", na=False)]["StockCode"].unique()

print(non_product_codes)

['POST' '15056BL' 'D' 'C2' 'M' 'BANK CHARGES' 'PADS' 'DOT' 'CRUK']


In [134]:
non_product_mask = ~df["StockCode"].str.match(r"^\d+[A-Z]?$", na=False)

non_product_count = non_product_mask.sum()

print("Number of non-product transactions:", non_product_count)

Number of non-product transactions: 2209


In [135]:
non_product_percentage = (non_product_count / len(df)) * 100

print("Percentage of non-product transactions:", non_product_percentage)

Percentage of non-product transactions: 0.5430333661923012


In [136]:
df.loc[non_product_mask, "StockCode"].value_counts()

StockCode
POST            1196
M                459
15056BL          296
C2               134
D                 77
CRUK              16
DOT               16
BANK CHARGES      12
PADS               3
Name: count, dtype: int64

In [137]:
df = df[df["StockCode"].str.match(r"^\d+[A-Z]?$", na=False)]

In [139]:
df.shape

(404580, 9)

The `StockCode` column represents product identifiers and has a high number of unique values. In total, the dataset contains **3,684 unique stock codes**, indicating a high-cardinality categorical feature.

Further inspection revealed that some stock codes do not correspond to actual products but instead represent transaction-related entries such as postage, discounts, or manual adjustments. Examples include codes such as **POST, D, M, C2, BANK CHARGES, DOT, CRUK, and PADS**.

Using pattern matching, stock codes that do not follow the standard product code format (typically numeric values with an optional letter suffix) were identified as non-product codes.

In total, **2,209 transactions (approximately 0.54% of the dataset)** were classified as non-product records.

For a product-level analysis, these entries are not meaningful because they represent services or adjustments rather than physical items. Therefore, these non-product transactions were removed from the dataset to ensure that only valid product purchases remain.

### 3.3 — Engineer a feature from Description

The `Description` column contains free text. Create a simple feature from it — for example, the word count of the description, or a flag for descriptions containing certain keywords (e.g., "SET", "PACK", "VINTAGE"). Show that your engineered feature has a meaningful relationship with `Quantity` or `UnitPrice`.

### Deliverable for Task 3

Analysis of categorical columns, a strategy for rare and high-cardinality categories, and one engineered feature with evidence of its usefulness.


In [141]:
df["desc_word_count"] = df["Description"].str.split().str.len()

df

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8768\3826105184.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["desc_word_count"] = df["Description"].str.split().str.len()


,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,is_cancelled,Country,desc_word_count
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,False,United Kingdom,5
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom,3
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,False,United Kingdom,5
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom,6
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,False,United Kingdom,5
...,...,...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680.0,False,France,5
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680.0,False,France,4
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680.0,False,France,4
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680.0,False,France,4


In [142]:
df['desc_word_count'].unique()

array([5, 3, 6, 4, 7, 2, 8, 1])

In [143]:
df.groupby("desc_word_count")["Quantity"].mean().sort_index()
# desc_word_count = 1 is outlier

desc_word_count
1    74.610169
2    13.842342
3    13.331031
4    11.742887
5    11.536604
6    12.150044
7    12.353139
8    14.585979
Name: Quantity, dtype: float64

In [144]:
df.groupby("desc_word_count")["UnitPrice"].mean().sort_index()

desc_word_count
1    1.807627
2    3.938546
3    2.646492
4    3.050189
5    2.865116
6    2.624040
7    3.075083
8    1.531243
Name: UnitPrice, dtype: float64

A feature called `desc_word_count` was created to represent the number of words in each product description.

The analysis shows that most product descriptions contain between 3 and 6 words, indicating relatively short and standardized naming patterns.

When examining the relationship between description length and `Quantity`, no strong relationship was observed for most products. Average quantities remain relatively stable across descriptions containing 2 to 8 words.

However, descriptions with only one word show unusually high average quantities. These cases likely correspond to special transaction-related entries rather than typical product descriptions.

Similarly, the relationship between description length and `UnitPrice` appears weak, as the average price remains relatively consistent across different description lengths.

Overall, the engineered feature provides insight into product description patterns but does not strongly influence quantity or price.

## Task 4: Class Imbalance — Predicting High-Value Customers (~25 minutes)

### 4.1 — Engineer a binary target

Create a customer-level dataset by aggregating transactions per `CustomerID`. Compute:
- Total revenue (`Quantity * UnitPrice`)
- Number of orders (unique `InvoiceNo` values)
- Number of distinct products purchased
- Date of first and last purchase

Define a binary target: a customer is **high-value** if their total revenue is in the top 10%. Label these as `1` and the rest as `0`.

```python
# Hint: compute total revenue per customer, then use a percentile threshold
customer_revenue = df.groupby("CustomerID").apply(
    lambda x: (x["Quantity"] * x["UnitPrice"]).sum()
).reset_index(name="total_revenue")
```


In [148]:
df["Revenue"] = df["Quantity"] * df["UnitPrice"]

customer_revenue = df.groupby("CustomerID")["Revenue"].sum().reset_index(name="total_revenue")
customer_revenue

C:\Users\ASUS\AppData\Local\Temp\ipykernel_8768\1935309179.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Revenue"] = df["Quantity"] * df["UnitPrice"]


,CustomerID,total_revenue
0,12346.0,0.00
1,12347.0,4310.00
2,12348.0,1437.24
3,12349.0,1457.55
4,12350.0,294.40
...,...,...
4357,18280.0,180.60
4358,18281.0,80.82
4359,18282.0,176.60
4360,18283.0,2088.93


In [149]:
customer_orders = df.groupby("CustomerID")["InvoiceNo"].nunique().reset_index(name="num_orders")
customer_orders

,CustomerID,num_orders
0,12346.0,2
1,12347.0,7
2,12348.0,4
3,12349.0,1
4,12350.0,1
...,...,...
4357,18280.0,1
4358,18281.0,1
4359,18282.0,3
4360,18283.0,16


In [150]:
df[df['CustomerID']==12346.0]

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,is_cancelled,Country,desc_word_count,Revenue
61619,541431,23166,MEDIUM CERAMIC TOP STORAGE JAR,74215,2011-01-18 10:01:00,1.04,12346.0,False,United Kingdom,5,77183.6
61624,C541433,23166,MEDIUM CERAMIC TOP STORAGE JAR,-74215,2011-01-18 10:17:00,1.04,12346.0,True,United Kingdom,5,-77183.6


In [152]:
customer_products = df.groupby("CustomerID")["StockCode"].nunique().reset_index(name="num_distinct_products")
customer_products

,CustomerID,num_distinct_products
0,12346.0,1
1,12347.0,103
2,12348.0,21
3,12349.0,72
4,12350.0,16
...,...,...
4357,18280.0,10
4358,18281.0,7
4359,18282.0,12
4360,18283.0,262


In [175]:
customer_dates = df.groupby("CustomerID")["InvoiceDate"].agg(
    first_purchase="min",
    last_purchase="max"
).reset_index()
customer_dates

,CustomerID,first_purchase,last_purchase
0,12346.0,2011-01-18 10:01:00,2011-01-18 10:17:00
1,12347.0,2010-12-07 14:57:00,2011-12-07 15:52:00
2,12348.0,2010-12-16 19:09:00,2011-09-25 13:13:00
3,12349.0,2011-11-21 09:51:00,2011-11-21 09:51:00
4,12350.0,2011-02-02 16:01:00,2011-02-02 16:01:00
...,...,...,...
4357,18280.0,2011-03-07 09:52:00,2011-03-07 09:52:00
4358,18281.0,2011-06-12 10:53:00,2011-06-12 10:53:00
4359,18282.0,2011-08-05 13:35:00,2011-12-02 11:43:00
4360,18283.0,2011-01-06 14:14:00,2011-12-06 12:02:00


In [176]:
customer_df = (
    customer_revenue
    .merge(customer_orders, on="CustomerID")
    .merge(customer_products, on="CustomerID")
    .merge(customer_dates, on="CustomerID")
)
customer_df

,CustomerID,total_revenue,num_orders,num_distinct_products,first_purchase,last_purchase
0,12346.0,0.00,2,1,2011-01-18 10:01:00,2011-01-18 10:17:00
1,12347.0,4310.00,7,103,2010-12-07 14:57:00,2011-12-07 15:52:00
2,12348.0,1437.24,4,21,2010-12-16 19:09:00,2011-09-25 13:13:00
3,12349.0,1457.55,1,72,2011-11-21 09:51:00,2011-11-21 09:51:00
4,12350.0,294.40,1,16,2011-02-02 16:01:00,2011-02-02 16:01:00
...,...,...,...,...,...,...
4357,18280.0,180.60,1,10,2011-03-07 09:52:00,2011-03-07 09:52:00
4358,18281.0,80.82,1,7,2011-06-12 10:53:00,2011-06-12 10:53:00
4359,18282.0,176.60,3,12,2011-08-05 13:35:00,2011-12-02 11:43:00
4360,18283.0,2088.93,16,262,2011-01-06 14:14:00,2011-12-06 12:02:00


In [177]:
threshold = customer_df["total_revenue"].quantile(0.9)
threshold
customer_df["high_value"] = (customer_df["total_revenue"] >= threshold).astype(int)

In [178]:
customer_df["high_value"].value_counts(normalize=True)

high_value
0    0.899817
1    0.100183
Name: proportion, dtype: float64

In [179]:
customer_df.groupby("high_value")["total_revenue"].mean()

high_value
0      837.599391
1    11406.223204
Name: total_revenue, dtype: float64

To analyze customer value, a customer-level dataset was created by aggregating transaction data for each `CustomerID`.

The following features were computed:
- **Total revenue**: calculated as the sum of `Quantity × UnitPrice`
- **Number of orders**: the number of unique invoices per customer
- **Number of distinct products** purchased
- **First and last purchase dates**

To define high-value customers, the total revenue distribution was examined. Customers whose total revenue falls within the **top 10%** were labeled as **high-value (1)**, while the remaining customers were labeled as **0**.

This binary target enables classification models to predict whether a customer belongs to the high-value segment.

### 4.2 — Measure the imbalance

- What is the class distribution (high-value vs. regular)?
- If a model always predicted "regular," what would its accuracy be?
- Why is accuracy a poor metric here?

The target variable shows a strong class imbalance. Approximately **90% of customers are labeled as regular (0)**, while **only about 10% are labeled as high-value (1)**.

If a model always predicted **"regular"**, it would classify every customer as class `0`. Since the majority of customers belong to this class, the model would still achieve an accuracy of approximately **90%**, even though it fails to identify any high-value customers.

This demonstrates why **accuracy is a poor metric for imbalanced classification problems**. A model could appear highly accurate simply by predicting the majority class every time, while completely ignoring the minority class.

In this case, correctly identifying high-value customers is important for business decisions. Therefore, evaluation metrics such as **precision, recall, F1-score, or ROC-AUC** are more appropriate than accuracy for assessing model performance.

### 4.3 — Apply resampling

Split the customer-level dataset into train and test sets (80/20). Then apply two resampling techniques to the **training set only**:

1. **Random oversampling** of the minority class
2. **Random undersampling** of the majority class

For each:
- Print the class distribution before and after resampling
- Train a simple model (e.g., `LogisticRegression` or `DecisionTreeClassifier`) on both the original and resampled training sets
- Evaluate on the **original (not resampled) test set** using precision, recall, and F1 for the high-value class


In [189]:
customer_df = customer_df.copy()

reference_date = customer_df["last_purchase"].max()

customer_df["customer_lifetime_days"] = (
    customer_df["last_purchase"] - customer_df["first_purchase"]
).dt.days

customer_df["recency_days"] = (
    reference_date - customer_df["last_purchase"]
).dt.days

In [190]:
X = customer_df[[
    "total_revenue",
    "num_orders",
    "num_distinct_products",
    "customer_lifetime_days",
    "recency_days"
]]

y = customer_df["high_value"]

In [191]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [194]:
print("Train distribution:")
print(y_train.value_counts(normalize=True))

Train distribution:
high_value
0    0.899685
1    0.100315
Name: proportion, dtype: float64


In [192]:
print(X_train.dtypes)

total_revenue             float64
num_orders                  int64
num_distinct_products       int64
customer_lifetime_days      int64
recency_days                int64
dtype: object


In [193]:
from sklearn.linear_model import LogisticRegression

model_original = LogisticRegression(max_iter=1000)
model_original.fit(X_train, y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [195]:
from imblearn.over_sampling import RandomOverSampler

ros = RandomOverSampler(random_state=42)

X_train_over, y_train_over = ros.fit_resample(X_train, y_train)

print("After oversampling:")
print(y_train_over.value_counts())

After oversampling:
high_value
0    3139
1    3139
Name: count, dtype: int64


In [196]:
model_over = LogisticRegression(max_iter=1000)

model_over.fit(X_train_over, y_train_over)

y_pred_over = model_over.predict(X_test)

from sklearn.metrics import classification_report

print("Oversampled model performance:")
print(classification_report(y_test, y_pred_over))

Oversampled model performance:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       786
           1       1.00      1.00      1.00        87

    accuracy                           1.00       873
   macro avg       1.00      1.00      1.00       873
weighted avg       1.00      1.00      1.00       873



In [197]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=42)

X_train_under, y_train_under = rus.fit_resample(X_train, y_train)

print("After undersampling:")
print(y_train_under.value_counts())

After undersampling:
high_value
0    350
1    350
Name: count, dtype: int64


In [198]:
model_under = LogisticRegression(max_iter=1000)

model_under.fit(X_train_under, y_train_under)

y_pred_under = model_under.predict(X_test)

print("Undersampled model performance:")
print(classification_report(y_test, y_pred_under))

Undersampled model performance:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       786
           1       0.99      1.00      0.99        87

    accuracy                           1.00       873
   macro avg       0.99      1.00      1.00       873
weighted avg       1.00      1.00      1.00       873



### 4.4 — Compare results

Create a summary table comparing:

| Method | Precision | Recall | F1 |
|---|---|---|---|
| No resampling | | | |
| Oversampling | | | |
| Undersampling | | | |

Which method best balances precision and recall for the high-value class? Write 3-5 sentences explaining your findings.


### Model Comparison

| Method | Precision | Recall | F1 |
|---|---|---|---|
| No resampling | 1.00 | 1.00 | 1.00 |
| Oversampling | 1.00 | 1.00 | 1.00 |
| Undersampling | 0.99 | 1.00 | 0.99 |

The results show that all three approaches achieve very high performance when predicting high-value customers. Both the original model and the oversampled model achieve perfect precision, recall, and F1-score, indicating that the model can clearly distinguish high-value customers based on the engineered features.

The undersampled model also performs very well, with slightly lower precision but nearly identical recall and F1-score. This suggests that reducing the majority class did not significantly harm the model's ability to identify high-value customers.

Overall, oversampling provides the best balance between precision and recall while preserving the full training dataset, making it a reliable strategy for handling class imbalance in this problem.

## Task 5: Data Leakage — Introduce, Detect, and Fix (~25 minutes)

### 5.1 — Intentionally introduce temporal leakage

The dataset spans December 2010 through December 2011. Suppose you want to predict whether a customer will make a purchase in December 2011 based on their behavior in earlier months.

First, do it **wrong**: randomly split all customer features (computed from the full date range) into train and test sets. Train a model and record its performance.


In [199]:
from sklearn.model_selection import train_test_split

X = customer_df.drop(columns=["CustomerID", "high_value"]).select_dtypes(include="number")
y = customer_df["high_value"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [200]:
from sklearn.linear_model import LogisticRegression

model_leak = LogisticRegression(max_iter=1000)

model_leak.fit(X_train, y_train)

y_pred_leak = model_leak.predict(X_test)

In [201]:
from sklearn.metrics import classification_report

print("Model with temporal leakage:")
print(classification_report(y_test, y_pred_leak))

Model with temporal leakage:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00       786
           1       1.00      1.00      1.00        87

    accuracy                           1.00       873
   macro avg       1.00      1.00      1.00       873
weighted avg       1.00      1.00      1.00       873



To demonstrate temporal leakage, the dataset was randomly split into training and test sets using features computed from the entire time period (December 2010 to December 2011).

This approach is incorrect because it allows the model to use information from the future when making predictions. As a result, the model indirectly learns patterns that would not be available in a real-world scenario.

The model achieved perfect performance (precision, recall, and F1-score of 1.00), which strongly suggests the presence of data leakage. Such unrealistically high performance indicates that the model is using future information that should not be available during prediction.

### 5.2 — Detect the leakage

- Check whether train and test sets contain features computed from overlapping time periods.
- Look for suspiciously high model performance (a sign of leakage).
- Compute feature-target correlations and identify any that seem too good to be true.


In [202]:
customer_df.select_dtypes(include="number").corr()["high_value"].sort_values(ascending=False)

high_value                1.000000
num_orders                0.542684
num_distinct_products     0.464958
customer_lifetime_days    0.412206
total_revenue             0.384227
CustomerID               -0.049605
recency_days             -0.227086
Name: high_value, dtype: float64

Several checks were performed to identify potential data leakage.

First, the dataset was randomly split into training and test sets while the features were computed using transactions from the entire time period (December 2010 to December 2011). This means that both train and test sets contain information derived from overlapping time periods, which introduces temporal leakage.

Second, the model achieved extremely high performance with precision, recall, and F1-score all equal to 1.00. Such perfect performance is highly suspicious in real-world machine learning tasks and strongly suggests the presence of leakage.

Finally, feature–target correlations were examined. Features such as `num_orders`, `num_distinct_products`, and `customer_lifetime_days` show moderately strong correlations with the target variable, indicating that customer activity is strongly associated with high-value status. However, the unrealistically high model performance suggests that the model is indirectly using future information when making predictions.

### 5.3 — Fix with a correct temporal split

Now do it **right**:
- Use data from December 2010 through September 2011 to compute customer features (the "observation window").
- Use data from October 2011 through December 2011 to create the target variable: did the customer make at least one purchase in this "prediction window"?
- Train the same model and compare performance.

```python
# Temporal split
observation_end = pd.Timestamp("2011-09-30")
prediction_start = pd.Timestamp("2011-10-01")

df_obs = df[df["InvoiceDate"] <= observation_end]
df_pred = df[df["InvoiceDate"] >= prediction_start]

In [204]:
### 5.3 — Fix with a correct temporal split


observation_end = pd.Timestamp("2011-09-30")
prediction_start = pd.Timestamp("2011-10-01")

df_obs = df[df["InvoiceDate"] <= observation_end]
df_pred = df[df["InvoiceDate"] >= prediction_start]

In [205]:
customer_features = df_obs.groupby("CustomerID").agg(
    total_revenue=("Revenue", "sum"),
    num_orders=("InvoiceNo", "nunique"),
    num_distinct_products=("StockCode", "nunique"),
    first_purchase=("InvoiceDate", "min"),
    last_purchase=("InvoiceDate", "max")
).reset_index()

In [206]:
customer_features = df_obs.groupby("CustomerID").agg(
    total_revenue=("Revenue", "sum"),
    num_orders=("InvoiceNo", "nunique"),
    num_distinct_products=("StockCode", "nunique"),
    first_purchase=("InvoiceDate", "min"),
    last_purchase=("InvoiceDate", "max")
).reset_index()

In [207]:
customer_target = df_pred.groupby("CustomerID").size().reset_index(name="purchases")

customer_target["target"] = (customer_target["purchases"] > 0).astype(int)

customer_target = customer_target[["CustomerID", "target"]]

In [208]:
customer_model = customer_features.merge(customer_target, on="CustomerID", how="left")

customer_model["target"] = customer_model["target"].fillna(0)

In [209]:

X = customer_model.drop(columns=[
    "CustomerID",
    "target",
    "first_purchase",
    "last_purchase"
])

y = customer_model["target"]


In [210]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [211]:
from sklearn.linear_model import LogisticRegression

model_temporal = LogisticRegression(max_iter=1000)

model_temporal.fit(X_train, y_train)

y_pred = model_temporal.predict(X_test)

In [212]:
from sklearn.metrics import classification_report

print("Model with correct temporal split:")
print(classification_report(y_test, y_pred))

Model with correct temporal split:
              precision    recall  f1-score   support

         0.0       0.66      0.83      0.73       352
         1.0       0.79      0.60      0.68       376

    accuracy                           0.71       728
   macro avg       0.72      0.71      0.71       728
weighted avg       0.73      0.71      0.71       728



To remove temporal leakage, a proper time-based split was implemented.

Customer features were computed only using transactions from December 2010 through September 2011 (the observation window). The target variable was then defined based on whether the customer made at least one purchase between October 2011 and December 2011 (the prediction window).

This ensures that the model only uses past information to predict future behavior. Compared to the earlier model with temporal leakage, the performance is expected to decrease, reflecting a more realistic evaluation scenario.

### 5.4 — Compare and reflect

Create a table comparing:

| Split method | Accuracy | Precision | Recall | F1 |
|---|---|---|---|---|
| Random (leaked) | | | | |
| Temporal (correct) | | | | |

Write 5-8 sentences explaining:
- Why did the leaked model perform better?
- What specific information leaked?
- Why is the temporal split the correct approach for this task?

### 5.4 — Comparing Random vs Temporal Split

| Split method | Accuracy | Precision | Recall | F1 |
|---|---|---|---|---|
| Random (leaked) | 1.00 | 1.00 | 1.00 | 1.00 |
| Temporal (correct) | 0.72 | 0.79 | 0.60 | 0.68 |

The model trained with the random split achieved perfect performance because it suffered from temporal leakage. The features used to train the model were computed using the entire dataset, including transactions from the prediction period. As a result, the model indirectly had access to future information when making predictions.

Specifically, customer features such as total revenue, number of orders, and recency were calculated using transactions that occurred during the same time period that the model was supposed to predict. This allowed the model to learn patterns that would not be available in a real-world prediction scenario.

When a proper temporal split was applied, features were computed only from past data (December 2010 to September 2011), and the target was defined using future behavior (October to December 2011). This prevents the model from seeing future information and produces a more realistic evaluation of model performance.

Although the performance decreased, the temporal split reflects how the model would behave in a real production environment and therefore provides a more reliable assessment.